# Generated by Django 4.2.16 on 2024-12-23 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.CharField(max_length=200)),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('task_created', models.DateField(default=datetime.date.today)),
                ('task_completed', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
