# Generated by Django 4.2.16 on 2024-12-23 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-task_created'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='task_completed',
            field=models.DateField(blank=True, null=True, verbose_name='Completed Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(help_text='Provide a task description.', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(help_text='Enter the task name.', max_length=50, verbose_name='Task Name'),
        ),
    ]
